name: MY FIRST GITHUB ACTION

on:
  push:
    branches:
        - master

env:
  username: ${{ secrets.USERNAME }}
  password: ${{ secrets.PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker images
        run: echo "$username  and my paassword is $password"
